import {Container} from "react-bootstrap";


function Home(props) {
    return (
        <Container className={props.className} fluid>
            <Container>
                <div className={"mt-5 mb-5"}>
                    <h1>Teachgram</h1>
                    <p><span>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Assumenda harum nam nisi. Accusamus accusantium blanditiis esse, iusto laborum magnam praesentium rem rerum soluta voluptate. Minus mollitia natus possimus repudiandae voluptatem.</span><span>Alias aliquid architecto aspernatur atque deleniti dignissimos ea eligendi eos facere illo, illum iusto laudantium maiores nihil nobis officia porro quas quia quis repudiandae rerum soluta sunt unde vero voluptas.</span><span>A ab corporis cum distinctio dolor dolorem eius expedita incidunt libero magnam maiores molestiae natus nemo, nostrum perspiciatis quis repellat rerum sapiente similique velit veritatis voluptas voluptate. Accusamus eaque, repudiandae!</span>
                    </p>
                    <p><span>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Ab ducimus facilis, minus nesciunt nobis, placeat qui repellendus reprehenderit sit tempore veniam voluptas voluptatem voluptatum? Nulla perspiciatis qui quos rem unde!</span><span>Architecto distinctio expedita molestiae quisquam? A animi dolor eos excepturi expedita fuga labore minima nihil perspiciatis, quas sapiente, sed voluptate voluptatum. A dicta, ea harum iste nemo nesciunt possimus. Harum.</span><span>Aliquid culpa distinctio excepturi id illum, magnam maiores perferendis perspiciatis porro provident qui quibusdam, sapiente similique. Cupiditate delectus doloremque dolores exercitationem magnam modi natus necessitatibus nihil quasi, quidem, quo, sapiente!</span><span>Accusamus amet animi consequatur corporis culpa cumque cupiditate debitis dignissimos, earum et illum impedit laudantium natus necessitatibus non nostrum numquam praesentium quam quasi quia quo recusandae repellendus ut velit veniam!</span><span>Ad at, fugiat hic id in incidunt quaerat quo saepe voluptates voluptatum. Accusantium earum eos esse facilis fuga impedit in, incidunt laudantium nemo numquam quasi quod, ratione rem totam vero.</span><span>Aliquid animi asperiores commodi laborum molestiae, non odio, quasi quidem quis, quos recusandae repudiandae rerum sed tempora ut! Ad aperiam atque dolores eius et modi tenetur veritatis? Iure, placeat, quisquam.</span>
                    </p>
                    <p><span>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Assumenda harum nam nisi. Accusamus accusantium blanditiis esse, iusto laborum magnam praesentium rem rerum soluta voluptate. Minus mollitia natus possimus repudiandae voluptatem.</span><span>Alias aliquid architecto aspernatur atque deleniti dignissimos ea eligendi eos facere illo, illum iusto laudantium maiores nihil nobis officia porro quas quia quis repudiandae rerum soluta sunt unde vero voluptas.</span><span>A ab corporis cum distinctio dolor dolorem eius expedita incidunt libero magnam maiores molestiae natus nemo, nostrum perspiciatis quis repellat rerum sapiente similique velit veritatis voluptas voluptate. Accusamus eaque, repudiandae!</span>
                    </p>
                </div>
                <div className={"mb-5"}>
                    <h2>How to use</h2>
                    <p><span>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Assumenda harum nam nisi. Accusamus accusantium blanditiis esse, iusto laborum magnam praesentium rem rerum soluta voluptate. Minus mollitia natus possimus repudiandae voluptatem.</span><span>Alias aliquid architecto aspernatur atque deleniti dignissimos ea eligendi eos facere illo, illum iusto laudantium maiores nihil nobis officia porro quas quia quis repudiandae rerum soluta sunt unde vero voluptas.</span><span>A ab corporis cum distinctio dolor dolorem eius expedita incidunt libero magnam maiores molestiae natus nemo, nostrum perspiciatis quis repellat rerum sapiente similique velit veritatis voluptas voluptate. Accusamus eaque, repudiandae!</span>
                    </p>
                    <p><span>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Ab ducimus facilis, minus nesciunt nobis, placeat qui repellendus reprehenderit sit tempore veniam voluptas voluptatem voluptatum? Nulla perspiciatis qui quos rem unde!</span><span>Architecto distinctio expedita molestiae quisquam? A animi dolor eos excepturi expedita fuga labore minima nihil perspiciatis, quas sapiente, sed voluptate voluptatum. A dicta, ea harum iste nemo nesciunt possimus. Harum.</span><span>Aliquid culpa distinctio excepturi id illum, magnam maiores perferendis perspiciatis porro provident qui quibusdam, sapiente similique. Cupiditate delectus doloremque dolores exercitationem magnam modi natus necessitatibus nihil quasi, quidem, quo, sapiente!</span><span>Accusamus amet animi consequatur corporis culpa cumque cupiditate debitis dignissimos, earum et illum impedit laudantium natus necessitatibus non nostrum numquam praesentium quam quasi quia quo recusandae repellendus ut velit veniam!</span><span>Ad at, fugiat hic id in incidunt quaerat quo saepe voluptates voluptatum. Accusantium earum eos esse facilis fuga impedit in, incidunt laudantium nemo numquam quasi quod, ratione rem totam vero.</span><span>Aliquid animi asperiores commodi laborum molestiae, non odio, quasi quidem quis, quos recusandae repudiandae rerum sed tempora ut! Ad aperiam atque dolores eius et modi tenetur veritatis? Iure, placeat, quisquam.</span>
                    </p>
                    <p><span>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Assumenda harum nam nisi. Accusamus accusantium blanditiis esse, iusto laborum magnam praesentium rem rerum soluta voluptate. Minus mollitia natus possimus repudiandae voluptatem.</span><span>Alias aliquid architecto aspernatur atque deleniti dignissimos ea eligendi eos facere illo, illum iusto laudantium maiores nihil nobis officia porro quas quia quis repudiandae rerum soluta sunt unde vero voluptas.</span><span>A ab corporis cum distinctio dolor dolorem eius expedita incidunt libero magnam maiores molestiae natus nemo, nostrum perspiciatis quis repellat rerum sapiente similique velit veritatis voluptas voluptate. Accusamus eaque, repudiandae!</span>
                    </p>
                </div>
                <div className={"mb-5"}>
                    <h2>Best practice</h2>
                    <p><span>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Assumenda harum nam nisi. Accusamus accusantium blanditiis esse, iusto laborum magnam praesentium rem rerum soluta voluptate. Minus mollitia natus possimus repudiandae voluptatem.</span><span>Alias aliquid architecto aspernatur atque deleniti dignissimos ea eligendi eos facere illo, illum iusto laudantium maiores nihil nobis officia porro quas quia quis repudiandae rerum soluta sunt unde vero voluptas.</span><span>A ab corporis cum distinctio dolor dolorem eius expedita incidunt libero magnam maiores molestiae natus nemo, nostrum perspiciatis quis repellat rerum sapiente similique velit veritatis voluptas voluptate. Accusamus eaque, repudiandae!</span>
                    </p>
                    <p><span>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Ab ducimus facilis, minus nesciunt nobis, placeat qui repellendus reprehenderit sit tempore veniam voluptas voluptatem voluptatum? Nulla perspiciatis qui quos rem unde!</span><span>Architecto distinctio expedita molestiae quisquam? A animi dolor eos excepturi expedita fuga labore minima nihil perspiciatis, quas sapiente, sed voluptate voluptatum. A dicta, ea harum iste nemo nesciunt possimus. Harum.</span><span>Aliquid culpa distinctio excepturi id illum, magnam maiores perferendis perspiciatis porro provident qui quibusdam, sapiente similique. Cupiditate delectus doloremque dolores exercitationem magnam modi natus necessitatibus nihil quasi, quidem, quo, sapiente!</span><span>Accusamus amet animi consequatur corporis culpa cumque cupiditate debitis dignissimos, earum et illum impedit laudantium natus necessitatibus non nostrum numquam praesentium quam quasi quia quo recusandae repellendus ut velit veniam!</span><span>Ad at, fugiat hic id in incidunt quaerat quo saepe voluptates voluptatum. Accusantium earum eos esse facilis fuga impedit in, incidunt laudantium nemo numquam quasi quod, ratione rem totam vero.</span><span>Aliquid animi asperiores commodi laborum molestiae, non odio, quasi quidem quis, quos recusandae repudiandae rerum sed tempora ut! Ad aperiam atque dolores eius et modi tenetur veritatis? Iure, placeat, quisquam.</span>
                    </p>
                    <p><span>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Assumenda harum nam nisi. Accusamus accusantium blanditiis esse, iusto laborum magnam praesentium rem rerum soluta voluptate. Minus mollitia natus possimus repudiandae voluptatem.</span><span>Alias aliquid architecto aspernatur atque deleniti dignissimos ea eligendi eos facere illo, illum iusto laudantium maiores nihil nobis officia porro quas quia quis repudiandae rerum soluta sunt unde vero voluptas.</span><span>A ab corporis cum distinctio dolor dolorem eius expedita incidunt libero magnam maiores molestiae natus nemo, nostrum perspiciatis quis repellat rerum sapiente similique velit veritatis voluptas voluptate. Accusamus eaque, repudiandae!</span>
                    </p>
                </div>

            </Container>
        </Container>);
}


export {Home}